### ISSUE TITLE
Clarify that the param.depends is decorating the get_plot function

### ISSUE THREAD

**Issue by jbednar** [bendoesdata/panel-altair-dashboard#1]
That's a great example; very clear and compelling! I'd recommend moving the `@pn.depends` line to be adjacent to the `def get_plot` function definition that it decorates to make it clear that it's decorating a function rather than declaring something that stands on its own. In both the Medium article and in the notebook, the relationship between those two items doesn't come through clearly to me, and I think it could confuse others.  Otherwise, looks great!

**Comment by bendoesdata** [comment]
Thanks! Yeah, good point. I tried moving the `@pn.depends` line below the function, but it's throwing a syntax error when I call the function at `dashboard=pn.Row(...)`.

Maybe I could add some comments and text in the Medium article to clarify it's decorating the function? Not sure why the error is showing only when I move the line. Checked indentation and it should be ok.

**Comment by jbednar** [comment]
It needs to be immediately above the function, as it is specifically applying to that particular function.  Putting comments in between the decorator and the function definition makes that harder to see, which is why the Python convention is to put decorators on the line immediately above the thing that they decorate, with nothing in between.  If you move the decorator somewhere else, it will then decorate whatever is on the subsequent line, so it needs to stay right where it is, just with no intervening comments (which Python doesn't care about, but humans will get confused by).

**Comment by jbednar** [comment]
E.g.:

```
# Define a function to create a plot, and tell Panel what that function "depends" on, 
# i.e., what should trigger a change in the chart.
@pn.depends(ticker.param.value, date_range_slider.param.value)
def get_plot(ticker, date_range):
```

**Comment by bendoesdata** [comment]
Ah ok, thanks that makes more sense now. I've moved the comments and adjusted the line so it's directly above the function. Repo just updated. Also added some text explaining how the decorator works to the Medium post.

Thanks for the flag!
